# Generated by Django 3.0.8 on 2022-02-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion de la publicacion'),
        ),
    ]
