# Generated by Django 3.0.8 on 2022-07-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Titulo de la publicacion')),
                ('contenido_noticia', models.TextField(blank=True, verbose_name='Contenido de la publicacion')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
                ('nombre_mascota', models.CharField(blank=True, max_length=200, verbose_name='Nombre Mascota')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado de la publicacion')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion de la publicacion')),
                ('imagen_antes', models.ImageField(blank=True, default='photos/perro1.jpg', null=True, upload_to='photos', verbose_name='PosterAntes')),
                ('imagen_despues', models.ImageField(blank=True, default='photos/perro1.jpg', null=True, upload_to='photos', verbose_name='PosterDespues')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=255, verbose_name='nombre del recurso')),
                ('imagen_noticia', models.ImageField(default='photos/perro1.jpg', upload_to='photos', verbose_name='imagenes')),
                ('ndescripcion', models.TextField(blank=True, verbose_name='Contenido ')),
                ('time', models.DateField(auto_now_add=True, verbose_name='Showtime')),
                ('nurl', models.CharField(max_length=255, verbose_name='play address')),
            ],
            options={
                'verbose_name': 'BlogNoti',
                'verbose_name_plural': 'BlogNoticias',
                'ordering': ['-time'],
            },
        ),
    ]
