# Generated by Django 3.0.8 on 2022-02-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=20, verbose_name='Cedula o Pasaporte')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('estado', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
        ),
    ]
