# Generated by Django 3.0.8 on 2022-07-07 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_denuncias_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncias',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
    ]
