# Generated by Django 3.0.8 on 2022-07-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias_Perros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('raza', models.CharField(blank=True, max_length=50, verbose_name='Raza')),
                ('edad', models.CharField(blank=True, max_length=20, verbose_name='edad')),
                ('vacunas', models.CharField(blank=True, max_length=10, verbose_name='Vacunas')),
                ('enfermedades', models.CharField(blank=True, max_length=100, verbose_name='Enfermedades')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Red Social')),
                ('imagen_mascota', models.ImageField(default='photos/perro1.jpg', upload_to='photos', verbose_name='imagenes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='adopciones.Categorias_Perros')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=20, verbose_name='Cedula o Pasaporte')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('perros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.Perros', verbose_name='Perros')),
            ],
        ),
    ]
