# Generated by Django 3.0.8 on 2022-07-30 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
