# Generated by Django 3.0.8 on 2022-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perros',
            name='imagen_mascota',
            field=models.ImageField(default='photos/perro1.jpg', upload_to='photos', verbose_name='imagenes'),
        ),
    ]
