# Generated by Django 3.0.8 on 2022-02-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('cantidad', models.CharField(blank=True, max_length=1000, verbose_name='Cantidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=20, verbose_name='Cedula o Pasaporte')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Productos', verbose_name='Productos')),
            ],
        ),
    ]
