# Generated by Django 3.0.8 on 2022-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='photos/donacion1.jpg', upload_to='photos', verbose_name='imagenes'),
        ),
    ]
