# Generated by Django 3.0.8 on 2022-07-31 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
