# Generated by Django 3.0.8 on 2022-02-18 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, verbose_name='Cedula o Pasaporte')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion Domiciliaria')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
