# Generated by Django 3.0.8 on 2022-07-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_perfil_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('voluntario', 'Voluntario')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
