# Generated by Django 3.0.8 on 2022-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_perfil_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('voluntario', 'Voluntario')], default='usuario', max_length=50),
        ),
    ]
