"""
Django settings for sabia project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.contrib.messages import  constants as message_constants


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j@i7ac0khclyp(n)^um)d(jr^5jxj(l0=5^+4i(t6o@f)u)_pq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['cristiansabia.pythonanywhere.com']

MESSAGE_STORAGE ="django.contrib.messages.storage.cookie.CookieStorage"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.home',
    'app.usuario',
    'app.denuncias',
    'app.adopciones',
    'app.donaciones',
    'app.blogs',
    'app.servicios',
    'app.cart',
    'app.orders',
    'app.cliente',
    'app.reports',
    #'app.payment',
    'crispy_forms',
    'paypal.standard.ipn',
    'pwa',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#TOMA DE SECION :
CRISPY_TEMPLATE_PACK = 'uni_form'
CART_SESSION_ID = 'cart'

ROOT_URLCONF = 'sabia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'sabia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {


            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'SabiaFinalDB',
            'USER': 'super',
            'PASSWORD': 'Tesis66Universidad',
            'HOST': 'cristianSabia-2655.postgres.pythonanywhere-services.com',
            'PORT': 12655,


        # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # 
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-EC'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

#USE_TZ = True

LANGUAGES=[
    ('en' ,'Ingles'),
    ('es' ,'Español')

]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


MEDIA_ROOT = os.path.join(BASE_DIR,'media')

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
PAYPAL_RECEIVER_EMAIL = 'sb-unzpk9185264@business.example.com'
PAYPAL_TEST = True

#PARA LOS MENSAJES DE BOOSTRAP
MESSAGE_TAGS ={
    message_constants.DEBUG: 'debug',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# <----------- Redireccion Login & LogOut ------------->

#LOGIN_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = 'pagina'
LOGOUT_REDIRECT_URL = '/'

# <----------- PWA - CONFIGURACION ------------->
PWA_APP_NAME = 'Santuario Bienestar Animal'
PWA_APP_SHORT_NAME = 'SABIA'
PWA_APP_DESCRIPTION = "Sabia_Mobil"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#FFFF'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '.' 
PWA_APP_ORIENTATION = 'any' 
PWA_APP_START_URL = './'
PWA_APP_STATUS_BAR_COLOR = 'default'

PWA_APP_ICONS = [ 
 {
    'src': '/static/img/icons/icon-48x48.png',
    'sizes': "48x48",
    'type': "image/png"
  }, 
  {
   'src': '/static/img/icons/icon-72x72.png',
   'sizes': "72x72",
   'type': "image/png"
  }, 
  {
   'src': '/static/img/icons/icon-96x96.png',
   'sizes': "96x96",
   'type': "image/png"
  }, 
    {
    'src': '/static/img/icons/icon-128x128.png',
    'sizes': '128x128',
    'type': "image/png",
        
        }, 
  {
    'src': '/static/img/icons/icon-144x144.png',
    'sizes': "144x144",
    'type': "image/png"
  },
  {
    'src': '/static/img/icons/icon-152x152.png',
    'sizes': "152x152",
    'type': "image/png"
  },
    {
    'src': '/static/img/icons/icon-192x192.png',
    'sizes': "192x192",
    'type': "image/png"
    },

    {
    'src': '/static/img/icons/icon-384x384.png',
    'sizes': "284x284",
    'type': "image/png"
    },
    {
    'src': '/static/img/icons/icon-512x512.png',
    'sizes': "512x512",
    'type': "image/png"
    },
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/icons/icon-48x48.png',
        'sizes': "48x48",
        'type': "image/png"
    },
    {
        'src': '/static/img/icons/icon-72x72.png',
        'sizes': "72x72",
        'type': "image/png"
    },
    {
        'src': '/static/img/icons/icon-96x96.png',
        'sizes': "96x96",
        'type': "image/png"
    },
    {
        'src': '/static/img/icons/icon-128x128.png',
        'sizes': '128x128',
        'type': "image/png",

    },
    {
        'src': '/static/img/icons/icon-144x144.png',
        'sizes': "144x144",
        'type': "image/png"
    },
    {
        'src': '/static/img/icons/icon-152x152.png',
        'sizes': "152x152",
        'type': "image/png"
    },
    {
        'src': '/static/img/icons/icon-192x192.png',
        'sizes': "192x192",
        'type': "image/png"
    },
    {
        'src': '/static/img/icons/icon-384x384.png',
        'sizes': "384x384",
        'type': "image/png"
    },
    {
        'src': '/static/img/icons/icon-512x512.png',
        'sizes': "512x512",
        'type': "image/png"
    },

]

PWA_APP_SPLASH_SCREEN = [{'src': '/static/img/icons/icon-512x512.png', 'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)' } ]
PWA_APP_DIR = 'ltr' 
PWA_APP_LANG = 'en-US'
PWA_APP_PERMISSIONS = [
    "notifications",
    "webRequest"
]
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, "serviceworker.js")
PWA_APP_SHORTCUTS = [{
    "name": "Adopciones",
    "description": "Adopta un perro",
    "url": "./",
    "icons": [
        {
            'src': '/static/images/icons/icon-192x192.png',
            'size': '192x192',
            "type": "image/png",
            "purpose": "any"
        }
    ]

}]
shortcuts = [{
    "name": "Adopciones",
    "description": "Adopta un perro",
    "url": "./",
    "icons": [
    {
        'src': '/static/images/icons/icon-192x192.png',
        'size': '192x192',
        "type": "image/png",
        "purpose": "any"
    }
]

}]
#PWA_APP_DEBUG_MODE = False
